version: "3.7"
services:

  validator-a:
    ports:
      - "9944:9944"
      - "9615:9615"
    image: parity/substrate
    networks:
      - internet
    command:
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000001"
      - "--base-path"
      - "/tmp/alice"
      - "--chain=staging"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "/dns/validator-b/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--log"
      - "sub-libp2p=trace"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"

  validator-b:
    ports:
      - "9945:9944"
    image: parity/substrate
    networks:
      - internet
    command:
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000002"
      - "--base-path"
      - "/tmp/bob"
      - "--chain=staging"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "/dns/validator-a/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--log"
      - "sub-libp2p=trace"

  light-c:
    ports:
      - "9946:9944"
    image: parity/substrate
    networks:
      - internet
    command:
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000003"
      - "--base-path"
      - "/tmp/light"
      - "--chain=staging"
      - "--port"
      - "30333"
      - "--light"
      - "--bootnodes"
      - "/dns/validator-a/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--bootnodes"
      - "/dns/validator-b/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--log"
      - "sub-libp2p=trace"

networks:
  internet: