name: Docker Compose CI

on:
    push:
      branches: [main]
    pull_request:
      branches: [main] 

jobs:
    docker_compose_ci:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - name: Build the docker-compose stack
            run: docker-compose up -d
            - name: Sleep
            uses: jakejarvis/wait-action@master
            with:
            time: '60s'
            - name: Check running containers
            run: docker ps
            - name: Run ci test suite
            ## todo: just for example,need actual test script.
            run: docker exec -it validator-a bash -c "scripts/local-test.sh"
            run: docker exec -it validator-b bash -c "scripts/local-test.sh"
            run: docker exec -it light-c bash -c "scripts/local-test.sh"
